const themeList = {
  클래식: {
    "--bgColor": "#FFFFFF",
    "--subBGColor": "#333333",
    "--outerFontColor": "#000000",
    "--innerFontColor": "#FFFFFF",
    "--selectedIconColor": "#000000",
    "--notSelectedIconColor": "#777777",
    "--footerBGColor": "#333333",
    "--footerIconColorDisabled": "#555555",
    "--footerIconColorEnabled": "#FFFFFF",
    "--footerBorderColor": "#333333",
  },
  라이트: {
    "--bgColor": "#FFFFFF",
    "--subBGColor": "#EEEEEE",
    "--outerFontColor": "#000000",
    "--innerFontColor": "#000000",
    "--selectedIconColor": "#000000",
    "--notSelectedIconColor": "#777777",
    "--footerBGColor": "#FFFFFF",
    "--footerIconColorDisabled": "#AAAAAA",
    "--footerIconColorEnabled": "#000000",
    "--footerBorderColor": "#AAAAAA",
  },
  다크: {
    "--bgColor": "#333333",
    "--subBGColor": "#444444",
    "--outerFontColor": "#FFFFFF",
    "--innerFontColor": "#FFFFFF",
    "--selectedIconColor": "#FFFFFF",
    "--notSelectedIconColor": "#777777",
    "--footerBGColor": "#333333",
    "--footerIconColorDisabled": "#555555",
    "--footerIconColorEnabled": "#FFFFFF",
    "--footerBorderColor": "#555555",
  },
};

export default themeList;
